version: '3.8'

services:
  api:
    build: .
    container_name: docdive-api
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - ./data:/app/data
      - ./app:/app/app  # For development hot-reloading
    environment:
      # Database settings
      - MONGODB_URI=mongodb://mongodb:27017
      - DB_NAME=${DB_NAME:-docdive}
      
      # LLM API keys
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - OPENAI_VERIFY_SSL=${OPENAI_VERIFY_SSL:-False}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_MODEL=${AZURE_OPENAI_MODEL}
      - AZURE_OPENAI_EMBEDDING_MODEL=${AZURE_OPENAI_EMBEDDING_MODEL}
      
      # Storage settings
      - UPLOAD_FOLDER=/app/data/uploads
      - VECTOR_DB_PATH=/app/data/chroma_db
      
      # Chunking settings
      - DEFAULT_CHUNK_SIZE=${DEFAULT_CHUNK_SIZE:-1000}
      - DEFAULT_CHUNK_OVERLAP=${DEFAULT_CHUNK_OVERLAP:-200}
      - DEFAULT_TOP_K=${DEFAULT_TOP_K:-4}
      - DEFAULT_LLM_MODEL=${DEFAULT_LLM_MODEL:-gpt-4o}
      - DEFAULT_EMBEDDING_MODEL=${DEFAULT_EMBEDDING_MODEL:-text-embedding-3-large}
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/system/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mongodb:
    image: mongo:6.0
    container_name: docdive-mongodb
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-docdive}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: ["--wiredTigerCacheSizeGB", "1"]

  locust:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docdive-locust
    ports:
      - "${LOCUST_PORT:-8089}:8089"
    volumes:
      - ./app/tests:/app/app/tests
    command: locust -f /app/app/tests/locustfile.py --host http://api:8000
    depends_on:
      api:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - LOCUST_USERS=${LOCUST_USERS:-10}
      - LOCUST_SPAWN_RATE=${LOCUST_SPAWN_RATE:-1}
      - LOCUST_RUN_TIME=${LOCUST_RUN_TIME:-1m}

volumes:
  mongodb_data:
    name: docdive-mongodb-data 