from setuptools import setup, find_packages

setup(
    name="document-qa-platform",
    version="1.0.0",
    packages=find_packages(),
    install_requires=[
        "fastapi==0.109.0",
        "uvicorn==0.27.0",
        "langchain==0.1.11",
        "langchain-community==0.0.27",
        "langchain-core==0.1.30",
        "langchain-openai==0.0.5",
        "pydantic==2.5.3",
        "python-multipart==0.0.9",
        "SQLAlchemy==2.0.25",
        "python-dotenv==1.0.0",
        "pypdf==4.0.1",
        "tiktoken==0.5.2",
        "transformers==4.38.1",
        "faiss-cpu==1.7.4",
        "locust==2.20.1",
        "anthropic==0.21.1",
        "openai==1.11.1",
        "pandas==2.1.3",
        "matplotlib==3.8.2",
        "pymongo==4.6.1",
        "markdown==3.5.1",
        "pytest==7.4.3",
        "httpx==0.25.2",
        "backoff==2.2.1",
        "chromadb==0.4.22",
        "pymupdf==1.23.19"
    ],
    author="Your Name",
    author_email="your.email@example.com",
    description="LLM-powered document search and Q&A platform with metrics dashboard",
    keywords="llm, document-search, qa, knowledge-base, fastapi",
    url="https://github.com/yourusername/document-qa-platform",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    python_requires=">=3.10",
) 